#!/usr/bin/env python3
"""Embed two binary files (index.html, app.js) as C byte arrays.

Usage: embed_static.py <out.c> <index.html> <app.js>

Generates symbols:
  const uint8_t sc_webshare_index_html[];
  const size_t  sc_webshare_index_html_len;
  const uint8_t sc_webshare_app_js[];
  const size_t  sc_webshare_app_js_len;
"""
import sys


def emit(name: str, data: bytes, out) -> None:
    out.write(f"const uint8_t sc_webshare_{name}[] = {{\n")
    for i, b in enumerate(data):
        if i % 16 == 0:
            out.write("    ")
        out.write(f"0x{b:02x},")
        out.write("\n" if (i + 1) % 16 == 0 else " ")
    if data and len(data) % 16 != 0:
        out.write("\n")
    out.write("};\n")
    out.write(f"const size_t sc_webshare_{name}_len = {len(data)};\n\n")


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    out_path, index_path, app_path = sys.argv[1:4]
    with open(index_path, "rb") as f:
        index_data = f.read()
    with open(app_path, "rb") as f:
        app_data = f.read()
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/* Auto-generated by embed_static.py - do not edit. */\n\n")
        out.write("#include <stddef.h>\n")
        out.write("#include <stdint.h>\n\n")
        emit("index_html", index_data, out)
        emit("app_js", app_data, out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
